
networks:
  inception:

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/wjhoe/data/wordpress:/var/www/html
    networks:
      - inception
    # secrets:
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - /home/wjhoe/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

# volumes:
#   db-data:
#   wp-data:

# Networks let services communicate with each other.
# You’re mapping host port 443 to container port 443, so traffic to your machine’s port 443 goes into the container’s port 443.
