services:
    nginx:
      build: requirements/nginx/
      container_name: nginx
      depends_on:
        - wordpress
        - mariadb
      ports:
        - "80:80"
      volumes:
        - ./web:/var/www/html
      networks:
        inception:
    wordpress:
      build: requirements/wordpress/
      container_name: wp-php
      volumes:
        - ./web:/var/www/html
      depends_on:
        - mariadb
      networks:
        inception:
    mariadb:
      build: requirements/mariadb/
      container_name: mariadb
      # restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword        # mandatory
        MYSQL_DATABASE: wordpress               # optional, WordPress DB
        MYSQL_USER: wpuser                      # optional, WordPress user
        MYSQL_PASSWORD: wppassword              # optional, WordPress user password
      volumes:
        - ./database:/var/lib/mysql
      networks:
        inception:

networks:
  inception: