
networks:
  inception:

services:
  nginx:
    container name:
    build: requirements/nginx
    depends_on:
      - wordpress
    networks: inception
    ports: "443:443"
  wordpress:
    container name:
    build: requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      wp-data: /home/wjhoe/data/wordpress
    networks: inception
    secrets:
  mariadb:
    container name:
    build: requirements/mariadb
    volumes:
      db-data: /home/wj
      hoe/data/mariadb
    networks: inception

volumes:
  db-data:
  wp-data:

# Networks let services communicate with each other.
# You’re mapping host port 443 to container port 443, so traffic to your machine’s port 443 goes into the container’s port 443.
