volumes:
    wordpress:
    mariadb:

networks:
  inception:
    name: imception

services:
    nginx:
      container_name: nginx
      build: requirements/nginx/
      depends_on:
        - wordpress
        - mariadb
      ports:
        - "80:80"
      volumes:
        - wordpress:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      restart:
        always
    wordpress:
      container_name: wp-php
      build: requirements/wordpress/
      volumes:
        - wordpress:/var/www/html
      depends_on:
        - mariadb
      env_file:
        - .env
      networks:
        - inception
      restart:
        always
    mariadb:
      container_name: mariadb
      build: requirements/mariadb/
      env_file:
        - .env
      volumes:
        - mariadb:/var/lib/mysql      
      networks:
        - inception
      restart:
        always
      