
networks:
  inception:
    name: inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/wjhoe/data/db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/wjhoe/data/wordpress
      o: bind

services:
    nginx:
      container_name: nginx
      build: requirements/nginx/
      depends_on:
        - wordpress
        - mariadb
      ports:
        - "443:443"
      volumes:
        - wp_data:/var/www/html
      networks:
        - inception
      restart:
        on-failure
    wordpress:
      container_name: wp-php
      build: requirements/wordpress/
      volumes:
        - wp_data:/var/www/html
      depends_on:
        - mariadb
      networks:
        - inception
      expose:
        - "9000"
      restart:
        on-failure
    mariadb:
      container_name: mariadb
      build: requirements/mariadb/
      volumes:
        - db_data:/var/lib/mysql      
      networks:
        - inception
      expose:
        - "3306"
      restart:
        on-failure


# volumes:
#   db-data:
#   wp-data:

# Networks let services communicate with each other.
# You’re mapping host port 443 to container port 443, so traffic to your machine’s port 443 goes into the container’s port 443.
