volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/wjhoe/inception/srcs/wordpress
                        o: bind
                        type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                        device: /home/wjhoe/inception/srcs/mariadb
                        o: bind
                        type: none

networks:
  inception:
    name: inception

services:
    nginx:
      container_name: nginx
      build: requirements/nginx/
      depends_on:
        - wordpress
        - mariadb
      ports:
        - "80:80"
      volumes:
        - /home/wjhoe/data/wordpress:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      restart:
        on-failure
    wordpress:
      container_name: wp-php
      build: requirements/wordpress/
      volumes:
        - /home/wjhoe/data/wordpress:/var/www/html
      depends_on:
        - mariadb
      env_file:
        - .env
      networks:
        - inception
      restart:
        on-failure
    mariadb:
      container_name: mariadb
      build: requirements/mariadb/
      env_file:
        - .env
      volumes:
        - /home/wjhoe/data/mariadb:/var/lib/mysql      
      networks:
        - inception
      # restart:

