
networks:
  inception:
    name: inception

services:
    nginx:
      container_name: nginx
      build: requirements/nginx/
      depends_on:
        - wordpress
        - mariadb
      ports:
        - "443:443"
      volumes:
        - /home/wjhoe/data/wordpress:/var/www/html
      networks:
        - inception
      restart:
        on-failure
    wordpress:
      container_name: wp-php
      build: requirements/wordpress/
      volumes:
        - /home/wjhoe/data/wordpress:/var/www/html
      depends_on:
        - mariadb
      networks:
        - inception
      restart:
        on-failure
    mariadb:
      container_name: mariadb
      build: requirements/mariadb/
      volumes:
        - /home/wjhoe/data/mariadb:/var/lib/mysql      
      networks:
        - inception
      # restart:


# volumes:
#   db-data:
#   wp-data:

# Networks let services communicate with each other.
# You’re mapping host port 443 to container port 443, so traffic to your machine’s port 443 goes into the container’s port 443.
